---
- name: Install default Apache Web Servers
  hosts: all
  become: yes

  tasks:
  - name: Install Apache
    yum: name=httpd state=latest
  - name: Start Apache and Enable
    service: name=httpd state=started enabled=yes
   
